config/routes.rb
Rails.application.routes.draw do
  root 'user_bios#index'
  devise_for :users
  resources :user_bios do
  resources :posts
  end
  scope 'posts/:post_id', as: 'post' do
    resources :comments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user_bio
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :user_bio
end

app/models/user_bio.rb
class UserBio < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create 
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to user_bio_post_path(@post.user_bio_id, @post)
    else
      render :new
    end

  end

  def destroy
    @comment.destroy
    redirect_to user_bio_post_path(@post.user_bio_id, @post)
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_bio
  before_action :set_post, only: [:show, :update, :edit, :destroy]
  def index
    @posts = @user_bio.posts
  end

  def show
  end

  def new
     @post = @user_bio.posts.new
     render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def update
    if @post.update(post_params)
      redirect_to user_bios_path
    else
      render :edit
    end
  end


  def create
    @post = @user_bio.posts.new(post_params)
    if @post.save
      redirect_to user_bios_path
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to user_bios_path
  end

  private 
  def set_post
    @post = Post.find(params[:id])
  end
    
    def set_bio
      @user_bio = UserBio.find(params[:user_bio_id])
    end

    def post_params
      params.require(:post).permit(:body)
    end 
end

app/controllers/user_bios_controller.rb
class UserBiosController < ApplicationController
  before_action :set_bio, only: [:show, :update, :edit, :destroy]
  def index
    @user_bio = current_user.user_bio
  end

  def show
  end

  def new
     @user_bio = UserBio.new
    #render partial: 'form'
  end

  def edit
  end

  def update
    if @user_bio.update(bio_params)
      redirect_to user_bios_path
    else
      render :edit
    end
  end


  def create
    @user_bio = current_user.create_user_bio(bio_params)
    if @user_bio.save
      redirect_to user_bios_path
    else
      render :new
    end
  end

  def destroy
    @user_bio.destroy
    redirect_to user_bios_path
  end

  private 
  def set_user
    @user = current_user
  end
    
    def set_bio
      @user_bio = UserBio.find(params[:id])
    end

    def bio_params
      params.require(:user_bio).permit(:first_name, :last_name, :location, :phone, :email, :bio)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_bios_helper.rb
module UserBiosHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
</hr>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Add A comment</h1>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%=render 'partials/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="ui blue three item inverted menu">
  <%= link_to "Home", user_bios_path, class: 'red item' %>
    <div class="item">
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'ui secondary simple button'%>
  </div>
</div>

app/views/posts/_form.html.erb
<h1><%= @post.id ? 'Edit' : 'Create' %></h1>
<hr />
<%= form_for [@user_bio, @post] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :body, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/show.html.erb
<h3><%= @post.body %></h3>

<%= link_to "Add comment", new_post_comment_path(@post) %>
<h2>Comments</h2>
    <% @post.comments.each do |comment| %>
      <%= render 'comments/comment', { comment: comment } %>
      <div class="column"> <%= link_to 'Delete', user_bio_post_path(@post), method: :delete %> 
<% end %> 

app/views/user_bios/_form.html.erb
<h1><%= @user_bio.id ? 'Edit Profile' : 'Add a Profile' %></h1>
<hr />
<%= form_for @user_bio do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true%>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, autofocus: true%>

    <%= f.label :location %>
    <%= f.text_field :location, required: true, autofocus: true%>

    <%= f.label :phone %>
    <%= f.text_field :phone, required: true, autofocus: true%>

    <%= f.label :email %>
    <%= f.text_field :email, required: true, autofocus: true%>

    <%= f.label :bio %>
    <%= f.text_area :bio, required: true, autofocus: true%>

    <%= f.submit %>
    <% end %>

app/views/user_bios/edit.html.erb
<%= render "form", user_bio: @user_bio%>

app/views/user_bios/index.html.erb
<% if @user_bio.nil?  %>
    <%= link_to "Create", new_user_bio_path %>
<% else %>
<h1> <%= @user_bio.first_name%>  <%= @user_bio.last_name%> </h1>
    <%= link_to "Edit", edit_user_bio_path(@user_bio) %>

      
<br>
        <%= @user_bio.email%><br>
        <%= @user_bio.phone%><br>
        <%= @user_bio.bio%><br>

        <%= link_to "Add post", new_user_bio_post_path(@user_bio) %>
        
        <div class="grid">
        <div class="ui equal width grid">
          <div class="column">Post</div>
          <div class="column"></div>
          <div class="column"></div>
        </div>

        <% @user_bio.posts.each do |post| %>

            <div class="ui equal width grid">
              <div class="column"><%= link_to post.body, [@user_bio,post] %></div>
              <div class="column"> <%= link_to 'Edit', edit_user_bio_post_path(@user_bio, post) %> </div>
              <div class="column"> <%= link_to 'Delete', [@user_bio,post], method: :delete, data: { confirm: "Are you sure?" }  %> 
                </div>
              <div id="likeBtn" class="ui labeled button" tabindex="0">
              <div class="ui green button" onclick="incrementValue(event)">
                     0
             </div>x
             <div class="ui red button" onclick="decrementValue(event)">
                    0
            </div>
              </div>
            </div>
            <%end%>
<% end %>


            

app/views/user_bios/new.html.erb
<%= render "form" %>

app/views/user_bios/show.html.erb
<h1>UserBios#show</h1>